// Generated by CoffeeScript 1.6.3
(function() {
  window.requestFileSystem = window.requestFileSystem || window.webkitRequestFileSystem;

  window.EditorFileSystem = (function() {
    function EditorFileSystem(root) {
      this.root = root;
    }

    EditorFileSystem.prototype.open = function(path, callback) {
      var failure, read, success,
        _this = this;
      failure = function(error) {
        return callback(null, null);
      };
      success = function(ent) {
        return ent.file(read, failure);
      };
      read = function(file) {
        var reader;
        reader = new FileReader();
        reader.onload = function() {
          var err, node;
          try {
            node = importJson(JSON.parse(reader.result));
          } catch (_error) {
            err = _error;
            callback(null, "error at read: " + err);
            return null;
          }
          return callback(node);
        };
        return reader.readAsText(file);
      };
      return this.root.getFile(path, {}, success, failure);
    };

    EditorFileSystem.prototype.save = function(path, node, callback) {
      var failure, write,
        _this = this;
      failure = function(error) {
        return callback(false, null);
      };
      write = function(entry) {
        return entry.createWriter(function(writer) {
          writer.truncate(0);
          return entry.createWriter(function(writer) {
            var blob, data;
            writer.onwriteend = function() {
              return callback(true);
            };
            data = JSON.stringify(exportJson(node));
            blob = new Blob([data], {
              type: "text/plain"
            });
            return writer.write(blob);
          });
        });
      };
      return this.root.getFile(path, {
        create: true
      }, write, failure);
    };

    return EditorFileSystem;

  })();

}).call(this);
