// Generated by CoffeeScript 1.6.3
(function() {
  window.exportJson = function(node) {
    var a;
    if (isList(node)) {
      return {
        type: 'list',
        label: node.label,
        list: (function() {
          var _i, _len, _ref, _results;
          _ref = node.list;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            a = _ref[_i];
            _results.push(exportJson(a));
          }
          return _results;
        })()
      };
    }
    if (isText(node)) {
      return {
        type: 'text',
        text: node.text,
        label: node.label
      };
    }
    if (isMark(node)) {
      return {
        type: 'mark',
        label: node.label
      };
    }
    throw "unimplemented node at json export";
  };

  window.importJson = function(json) {
    var a, list, node;
    switch (json.type) {
      case 'list':
        list = (function() {
          var _i, _len, _ref, _results;
          _ref = json.list;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            a = _ref[_i];
            _results.push(importJson(a));
          }
          return _results;
        })();
        node = newList(list, json.label);
        return node;
      case 'text':
        node = newText(json.text, json.label);
        return node;
      case 'mark':
        node = newMark(json.label);
        return node;
      default:
        throw "unimplemented node at json import";
    }
  };

}).call(this);
