// Generated by CoffeeScript 1.6.3
(function() {
  window.exportJson = function(node) {
    var a;
    switch (node.type) {
      case 'list':
        return {
          type: 'list',
          label: node.label,
          list: (function() {
            var _i, _len, _ref, _results;
            _ref = node.list;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              a = _ref[_i];
              _results.push(exportJson(a));
            }
            return _results;
          })()
        };
      case 'text':
        return {
          type: 'text',
          text: node.text
        };
      case 'cr':
        return {
          type: 'cr'
        };
      default:
        throw "unimplemented node at json export";
    }
  };

  window.importJson = function(json) {
    var a, list, node;
    switch (json.type) {
      case 'list':
        list = (function() {
          var _i, _len, _ref, _results;
          _ref = json.list;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            a = _ref[_i];
            _results.push(importJson(a));
          }
          return _results;
        })();
        node = new ListNode(list);
        node.label = json.label;
        return node;
      case 'text':
        return text(json.text);
      case 'cr':
        return cr();
      default:
        throw "unimplemented node at json import";
    }
  };

}).call(this);
