// Generated by CoffeeScript 1.6.3
(function() {
  window.keyboardEvents = function(canvas, callback) {
    var node;
    node = document.createElement("input");
    node.style.position = "absolute";
    node.style.left = "-10000px";
    canvas.parentNode.insertBefore(node, canvas);
    node.addEventListener('keydown', function(ev) {
      var keyCode, keyhandler;
      keyCode = ev.keyCode;
      if (keyCode === 9) {
        ev.preventDefault();
      }
      node.value = "";
      keyhandler = function() {
        return callback(keyCode, node.value);
      };
      return setTimeout(keyhandler, 0);
    });
    node.focus();
    return canvas.addEventListener('click', function() {
      return node.focus();
    });
  };

}).call(this);
