// Generated by CoffeeScript 1.6.3
(function() {
  var Selection, leftSelection, rightSelection, textleft, textright, travelLeft, travelRight;

  window.addEventListener('load', function() {
    var bc, canvas, draw, drawBox, insertMode, mode, model, mouse, node_split, over, selectMode, selection;
    canvas = autoResize(document.getElementById('editor'));
    bc = canvas.getContext('2d');
    model = list(text("define"), list(text("factorial"), text("n")), cr(), list(text("if"), list(text("="), text("n"), text("0")), text("1"), cr(), list(text("*"), text("n"), list(text("factorial"), list(text("-"), text("n"), text("1"))))));
    mouse = mouseInput(canvas);
    window.model = model;
    over = null;
    mode = null;
    selection = textright(leftSelection(model));
    selection.mark();
    insertMode = function(keyCode, txt) {
      var head, lb, obj, range, start, stop, target, tb, tnode, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8;
      selection.unmark();
      if (keyCode === 27) {
        mode = selectMode;
      }
      if (keyCode === 13) {
        if (selection.target.type === 'text') {
          if ((0 < (_ref = selection.head) && _ref < selection.target.length)) {
            node_split(selection.target, selection.head);
            _ref1 = selection.target.getRange(), target = _ref1.target, stop = _ref1.stop;
            selection = new Selection(target, stop, stop);
          } else if (selection.head === selection.target.length) {
            _ref2 = selection.target.getRange(), target = _ref2.target, stop = _ref2.stop;
            selection = new Selection(target, stop, stop);
          } else if (selection.head === 0) {
            _ref3 = selection.target.getRange(), target = _ref3.target, start = _ref3.start;
            selection = new Selection(target, start, start);
          }
        }
        selection.target.put(selection.head, listbuffer(cr()));
        head = selection.head + 1;
        selection.update(head, head);
      }
      if (txt === " ") {
        if (selection.target.type === 'text') {
          head = selection.head, target = selection.target;
          if (head === target.length) {
            _ref4 = target.getRange(), target = _ref4.target, stop = _ref4.stop;
            selection = new Selection(target, stop, stop);
          } else if (head === 0) {
            _ref5 = target.getRange(), target = _ref5.target, start = _ref5.start;
            selection = new Selection(target, start, start);
          } else {
            selection = node_split(target, head);
          }
        }
      }
      if (txt === "(") {
        if (selection.target.type === 'text') {
          head = selection.head, target = selection.target;
          if (head === target.length) {
            _ref6 = target.getRange(), target = _ref6.target, stop = _ref6.stop;
            selection = new Selection(target, stop, stop);
          } else if (head === 0) {
            _ref7 = target.getRange(), target = _ref7.target, start = _ref7.start;
            selection = new Selection(target, start, start);
          } else {
            selection = node_split(target, head);
            _ref8 = target.getRange(), target = _ref8.target, stop = _ref8.stop;
            selection = new Selection(target, stop, stop);
          }
        }
        obj = list();
        selection.target.put(selection.head, listbuffer(obj));
        selection.target = obj;
        selection.update(0, 0);
      }
      if (txt === ")") {
        if (selection.target.type === 'text') {
          target = selection.target.getRange().target;
        } else {
          target = selection.target;
        }
        if ((range = target.getRange()) != null) {
          selection = new Selection(range.target, range.stop, range.stop);
        }
      } else if (txt.length > 0) {
        if (selection.target.type === 'text') {
          tb = textbuffer(txt);
          selection.target.put(selection.head, tb);
          head = selection.head + txt.length;
          selection.update(head, head);
        }
        if (selection.target.type === 'list') {
          tnode = text(txt);
          lb = listbuffer(tnode);
          selection.target.put(selection.head, lb);
          selection = new Selection(tnode, txt.length, txt.length);
        }
      }
      return selection.mark();
    };
    node_split = function(target, index) {
      var node, stop, _ref;
      node = text(target.kill(index, target.length).text);
      _ref = target.getRange(), target = _ref.target, stop = _ref.stop;
      target.put(stop, listbuffer(node));
      return new Selection(node, 0, 0);
    };
    insertMode.tag = "insert";
    selectMode = function(keyCode, text) {
      selection.unmark();
      if (text === 'i') {
        mode = insertMode;
      }
      if (text === 'l') {
        if (selection.head < selection.target.length && selection.target.type === 'text') {
          selection.update(selection.head + 1, selection.head + 1);
        } else {
          selection = textright(travelRight(selection));
        }
      }
      if (text === 'w') {
        selection = textright(travelRight(selection));
      }
      if (text === 'e') {
        if (selection.target.type !== 'text' || selection.head === selection.target.length) {
          selection = textright(travelRight(selection));
        }
        if (selection.target.type === 'text') {
          selection.update(selection.target.length, selection.target.length);
        }
      }
      if (text === 'h') {
        if (0 < selection.head && selection.target.type === 'text') {
          selection.update(selection.head - 1, selection.head - 1);
        } else {
          selection = textleft(travelLeft(selection));
        }
      }
      if (text === 'b') {
        if (selection.target.type !== 'text' || selection.head === 0) {
          selection = textleft(travelLeft(selection));
        }
        if (selection.target.type === 'text') {
          selection.update(0, 0);
        }
      }
      return selection.mark();
    };
    selectMode.tag = "select";
    mode = selectMode;
    keyboardEvents(canvas, function(keyCode, text) {
      return mode(keyCode, text);
    });
    draw = function() {
      bc.fillStyle = "#aaa";
      bc.fillRect(0, 0, canvas.width, canvas.height);
      bc.textBaseline = "middle";
      model.layout(bc);
      model.x = 50;
      model.y = 50;
      over = model.mousemotion.apply(model, mouse.point);
      model.draw(bc);
      bc.fillText("press (h,l,w,e,b) -keys to try basic motions", 50, 10);
      bc.fillText("(i and ESC) to enter and leave insert -mode", 50, 30);
      bc.fillText("mode: " + mode.tag, 500, 10);
      return requestAnimationFrame(draw);
    };
    drawBox = function(x, y, w, h) {
      bc.beginPath();
      bc.rect(x, y, w, h);
      bc.fill();
      return bc.stroke();
    };
    return draw();
  });

  Selection = (function() {
    function Selection(target, head, tail) {
      this.target = target;
      this.head = head;
      this.tail = tail;
      this.update(this.head, this.tail);
    }

    Selection.prototype.update = function(head, tail) {
      this.head = head;
      this.tail = tail;
      this.start = Math.min(this.head, this.tail);
      return this.stop = Math.max(this.head, this.tail);
    };

    Selection.prototype.mark = function() {
      return this.target.selection = this;
    };

    Selection.prototype.unmark = function() {
      return this.target.selection = null;
    };

    return Selection;

  })();

  leftSelection = function(target) {
    return new Selection(target, 0, 0);
  };

  rightSelection = function(target) {
    return new Selection(target, target.length, target.length);
  };

  textleft = function(selection) {
    var node, start, stop, target;
    target = selection.target, start = selection.start, stop = selection.stop;
    if (target.type !== 'text' && 0 < start) {
      node = target.list[start - 1];
      if (node.type === 'text') {
        return new Selection(node, node.length, node.length);
      }
    }
    return selection;
  };

  textright = function(selection) {
    var node, start, stop, target;
    target = selection.target, start = selection.start, stop = selection.stop;
    if (target.type !== 'text' && stop < target.length) {
      node = target.list[stop];
      if (node.type === 'text') {
        return new Selection(node, 0, 0);
      }
    }
    return selection;
  };

  travelLeft = function(selection) {
    var head, node, start, target, _ref, _ref1;
    target = selection.target, head = selection.head;
    if (target.type === 'text') {
      _ref = target.getRange(), start = _ref.start, target = _ref.target;
      return travelLeft(new Selection(target, start, start));
    }
    if (target.type === 'list') {
      if (0 < head) {
        node = target.list[head - 1];
        if (node.type === 'list' || node.type === 'text') {
          return rightSelection(node);
        }
        return new Selection(target, head - 1, head - 1);
      } else if (target.parent != null) {
        _ref1 = target.getRange(), start = _ref1.start, target = _ref1.target;
        return new Selection(target, start, start);
      }
    }
    return selection;
  };

  travelRight = function(selection) {
    var head, node, stop, target, _ref, _ref1;
    target = selection.target, head = selection.head;
    if (target.type === 'text') {
      _ref = target.getRange(), stop = _ref.stop, target = _ref.target;
      return travelRight(new Selection(target, stop, stop));
    }
    if (target.type === 'list') {
      if (head < target.length) {
        node = target.list[head];
        if (node.type === 'list' || node.type === 'text') {
          return leftSelection(node);
        }
        return new Selection(target, head + 1, head + 1);
      } else if (target.parent != null) {
        _ref1 = target.getRange(), stop = _ref1.stop, target = _ref1.target;
        return new Selection(target, stop, stop);
      }
    }
    return selection;
  };

}).call(this);
