// Generated by CoffeeScript 1.6.3
(function() {
  window.addEventListener('load', function() {
    var bc, canvas, draw;
    canvas = autoResize(document.getElementById('editor'));
    bc = canvas.getContext('2d');
    return (draw = function() {
      bc.fillStyle = "#aaa";
      bc.fillRect(0, 0, canvas.width, canvas.height);
      bc.fillStyle = "black";
      bc.fillRect(50, 50, 150, 10);
      return requestAnimationFrame(draw);
    })();
  });

}).call(this);
