// Generated by CoffeeScript 1.6.3
(function() {
  if (window.AudioContext == null) {
    window.AudioContext = window.webkitAudioContext;
  }

  window.mouseInput = function(canvas) {
    var mouse, mousemove;
    mouse = {
      point: vec2.create()
    };
    document.addEventListener('mousemove', mousemove = function(e) {
      var rect;
      rect = canvas.getBoundingClientRect();
      mouse.point[0] = (e.clientX - rect.left) / rect.width * canvas.width;
      return mouse.point[1] = (e.clientY - rect.top) / rect.height * canvas.height;
    });
    return mouse;
  };

  window.autoResize = function(canvas) {
    var resize;
    window.addEventListener('resize', resize = function() {
      canvas.width = canvas.clientWidth;
      return canvas.height = canvas.clientHeight;
    });
    resize();
    return canvas;
  };

  window.every = function(secs, func) {
    return setInterval(func, secs * 1000);
  };

  window.gameLoop = function(fps, func) {
    return setInterval((function() {
      return func(1 / fps);
    }), 1000 / fps);
  };

}).call(this);
